#!/bin/bash
shopt -s failglob
#umask 0770

ROBBIE_CONF=/etc/Robbie.d

if [ ! -d /tmp/Robbie ]
then
   mkdir /tmp/Robbie
fi

if [ -e /tmp/Robbie.Run ]
then
   logger "Robbie not run as it is already running, delete /tmp/Robbie.Run if it is not"
   echo "Robbie not run as it is already running, delete /tmp/Robbie.Run if it is not"
   exit 2
else
   touch /tmp/Robbie.Run
fi

cd /var/Robbie

rm Robbie.table &>/dev/null
now=`date +%s`
let base_time=now-300
#let now=now-3000
#let now=now+30000
#echo $now

for f in $ROBBIE_CONF/*.interval
do
#   echo $f
   filename=`basename $f .interval`
   updatetime=`cat $f`
   if [ ! -s $filename.time ]
   then
      echo -n "<tr><td>$filename</td><td></td><td>No Files since last restart</td><td>$updatetime</td></tr>" >>Robbie.table
      logger "Error: No time file for $filename"
   else
      last_update=`cat $filename.time`

      let expected_update=base_time-updatetime
#      echo $expected_update
      echo -n "<tr><td>$filename</td><td> " `date -j -f%s $last_update` " </td><td>" >>Robbie.table

      if [ $last_update -lt $expected_update ]
      then
         if [ -e /var/Robbie/$filename.not_working ]
         then
            echo -n "Not Working" >>Robbie.table
         else
            rm /var/Robbie/$filename.working &>/dev/null
            echo $last_update >/var/Robbie/$filename.not_working
            echo -n "<b>Not Working</b>">>Robbie.table
#            mail -s "$filename Not Working" Geoffrey_Kirk@Trimble.com </dev/null &>/dev/null
         fi
      else
         if [ -e /var/Robbie/$filename.working ]
         then
            echo -n "Working" >>Robbie.table
         else
            rm /var/Robbie/$filename.not_working &>/dev/null
            echo $last_update >/var/Robbie/$filename.working
            echo -n "<b>Working</b>" >>Robbie.table
#            mail -s "$filename Now Working" Geoffrey_Kirk@Trimble.com </dev/null &>/dev/null
         fi
      fi
   echo -n "</td>" >>Robbie.table
   echo -n "<td>$updatetime</td>" >>Robbie.table
   echo "</tr>" >>Robbie.table
   fi
done


for f in *.time
do
#   echo $f
   filename=`basename $f .time`
   if [ ! -s $ROBBIE_CONF/$filename.interval ]
   then
      echo -n "<tr><td>$filename</td><td></td><td>No Interval Files</td></tr>" >>Robbie.table
      logger "Internal Error: No intervale file for $filename"
   fi
done

echo "<html><head><title>Robbie the Status</title></head><body><table border="1">" >/Library/WebServer/Documents/Robbie/index.html
echo "Last Status Update:" `date`  "<p>" >>/Library/WebServer/Documents/Robbie/index.html
echo "<tr><th>Base</th><th>Last Update</th><th>Status</th><th>Expected</th></tr>" >>/Library/WebServer/Documents/Robbie/index.html
chmod 0770 Robbie.table
sort Robbie.table >> /Library/WebServer/Documents/Robbie/index.html
echo "</table></html>" >>/Library/WebServer/Documents/Robbie/index.html

rm /tmp/Robbie.Run &>/dev/null

echo "Content-type: text/html";
echo "Cache-Control: no-store"
echo ""
cat /Library/WebServer/Documents/Robbie/index.html
