#! /bin/bash 
PLUGIN_DIR=`dirname $0`
if [ $3 ] ; then
   $PLUGIN_DIR/check_http_v2 -S -I $2 -p $3 -H "$1" -u "https://$HOSTADDRESS$" -j CONNECT -C 0
else
   $PLUGIN_DIR/check_http -I $1 --ssl -C 0
fi  
