#! /bin/bash
cat <<HEAD
Content-type: text/html

<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="utf-8" />
   <title>Trimble Antenna.ini Antenna Viewer</title>
   <meta name="generator" content="BBEdit 10.5" />
</head>
<body>
HEAD

antenna=`echo "$QUERY_STRING" | sed -n 's/^.*antenna=\([^&]*\).*$/\1/p' | sed "s/%20/ /g"| sed "s/+/ /g"| sed "s/%2F/\//g"`

./antenna.ini.py --html --antenna "$antenna"
cat <<EOF1
<br/>
</body>
</html>
EOF1
